version: "2"
checks:
  method-lines:
    config:
      threshold: 50
engines:
  checkstyle:
    enabled: true
    channel: "beta"

ratings:
  paths:
  - "src/**.js"

  plugins:
    eslint:
      enabled: true
      config:
        config: .eslintrc.js